# Generated by Django 5.2.6 on 2025-09-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirtimeTopUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mtn", "mtn"),
                            ("airtel", "airtel"),
                            ("glo", "glo"),
                            ("etisalat", "etisalat"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone_number", models.IntegerField()),
                ("reference_id", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
