# Generated by Django 5.2.6 on 2025-11-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimetopup',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
