# Generated by Django 5.2.6 on 2025-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airtimetopup",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
