# Generated by Django 5.2.6 on 2025-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_airtimetopup_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billerCode', models.CharField()),
                ('amount', models.IntegerField()),
                ('biller_name', models.CharField(choices=[('ikeja-electric', 'ikeja-electric'), ('eko-electric', 'eko-electric'), ('kano-electric', 'kano-electric'), ('portharcourt-electric', 'portharcourt-electric'), ('jos-electric', 'jos-electric'), ('ibadan-electric', 'ibadan-electric'), ('kaduna-electric', 'kaduna-electric'), ('abuja-electric', 'abuja-electric'), ('enugu-electric', 'enugu-electric'), ('benin-electric', 'benin-electric'), ('aba-electric', 'aba-electric'), ('yola-electric', 'yola-electric')], max_length=30)),
                ('meter_type', models.CharField(choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=20)),
                ('phone_number', models.CharField()),
                ('reference_id', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JAMBRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billerCode', models.CharField()),
                ('exam_type', models.CharField(choices=[('utme-mock', 'utme-mock'), ('utme-no-mock', 'utme-no-mock')], max_length=20)),
                ('phone_number', models.CharField()),
                ('reference_id', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAECRegitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField()),
                ('reference_id', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WAECResultChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField()),
                ('reference_id', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='airtimetopup',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
