# Generated by Django 5.2.6 on 2026-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_airtimetopup_request_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityPaymentCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biller",
                    models.CharField(
                        choices=[
                            ("ikeja-electric", "ikeja-electric"),
                            ("eko-electric", "eko-electric"),
                            ("kano-electric", "kano-electric"),
                            ("portharcourt-electric", "portharcourt-electric"),
                            ("jos-electric", "jos-electric"),
                            ("ibadan-electric", "ibadan-electric"),
                            ("kaduna-electric", "kaduna-electric"),
                            ("abuja-electric", "abuja-electric"),
                            ("enugu-electric", "enugu-electric"),
                            ("benin-electric", "benin-electric"),
                            ("aba-electric", "aba-electric"),
                            ("yola-electric", "yola-electric"),
                        ],
                        max_length=30,
                    ),
                ),
                ("meter_number", models.CharField(max_length=20)),
                (
                    "meter_type",
                    models.CharField(
                        choices=[("prepaid", "prepaid"), ("postpaid", "postpaid")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="electricitypayment",
            name="billerCode",
            field=models.CharField(max_length=20),
        ),
    ]
