# Generated by Django 5.2.6 on 2026-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_withdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
