# Generated by Django 5.2.6 on 2025-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_electricitypayment_jambregistration_waecregitration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airtimetopup',
            old_name='reference_id',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='electricitypayment',
            old_name='reference_id',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jambregistration',
            old_name='reference_id',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='waecregitration',
            old_name='reference_id',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='waecresultchecker',
            old_name='reference_id',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='request_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
