# Generated by Django 5.2.6 on 2026-04-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_withdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricitypaymentcustomers",
            name="meter_number",
            field=models.CharField(max_length=15),
        ),
    ]
