# Generated by Django 5.2.6 on 2026-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_electricitypaymentcustomer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airteldatatopup",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="airtime2cash",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="airtimetopup",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="dstvpayment",
            name="billersCode",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="dstvpayment",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="electricitypayment",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="etisalatdatatopup",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="glodatatopup",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="gotvpayment",
            name="billersCode",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="gotvpayment",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="jambregistration",
            name="billerCode",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="jambregistration",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="mtndatatopup",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="showmaxpayment",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="startimespayment",
            name="billersCode",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="startimespayment",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="waecregitration",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="waecresultchecker",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
    ]
