# Generated by Django 5.2.6 on 2026-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_electricitypaymentcustomers_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airteldatatopup',
            name='plan',
            field=models.CharField(choices=[('N50 25MB - 1 day', 'airt-50'), ('N100 75MB - 1 day', 'airt-100'), ('N200 200MB - 3 days', 'airt-200'), ('N300 350MB - 7 days', 'airt-social-300-3'), ('N500 750MB - 14 days', 'airt-500'), ('N1000 1.5GB - 30 days', 'airt-1000-7'), ('N1500 3GB - 30 days', 'airt-1500-30'), ('N2000 4.5GB - 30 days', 'airt-2000'), ('N3000 8GB - 30 days', 'airt-3000'), ('N4000 11GB - 30 days', 'airt-4000'), ('N5000 15GB - 30 days', 'airt-5000'), ('N1500 6GB Binge - 7 days', 'airt-1500-2'), ('N10000 40GB - 30 days', 'airt-10000'), ('N15000 75GB - 30 days', 'airt-15000'), ('N20000 110GB - 30 days', 'airt-20000'), ('N600 1GB - 14 days', 'airt-600'), ('N1000 1.5GB - 7 days', 'airt-1000-7'), ('N2000 7GB - 7 days', 'airt-2500-7'), ('N5000 25GB - 7 days', 'airt-5000-7'), ('N400 1.5GB - 1 day', 'airt-350-500'), ('N800 3.5GB - 2 days', 'airt-750-2'), ('N6000 23GB - 30 days', 'airt-6000-30')], max_length=100),
        ),
        migrations.AlterField(
            model_name='etisalatdatatopup',
            name='plan',
            field=models.CharField(choices=[('N100 100MB - 1 day', '9mobile-sme-data-100mb'), ('N200 650MB - 1 day', '9mobile-sme-data-200mb'), ('N500 500MB - 30 days', '9mobile-sme-data-500mb'), ('N1000 1.5GB - 30 days', '9mobile-sme-data-1gb'), ('N2000 4.5GB - 30 days', '9mobile-sme-data-2gb'), ('N5000 15GB - 30 days', '9mobile-sme-data-5gb'), ('N10000 40GB - 30 days', '9mobile-sme-data-10gb'), ('N15000 75GB - 30 days', '9mobile-sme-data-15gb'), ('N27500 30GB - 90 days', '9mobile-sme-data-25gb'), ('N55000 60GB - 180 days', '9mobile-sme-data-50gb'), ('N110000 120GB - 365 days', '9mobile-sme-data-100gb'), ('N300 1GB + 100MB - 1 day', '9mobile-sme-data-1gb'), ('N2500 11GB - 30 days', '9mobile-sme-data-20gb'), ('N7000 35GB - 30 days', '9mobile-sme-data-25gb'), ('N20000 125GB - 30 days', '9mobile-sme-data-100gb'), ('N1000 4GB - 30 days', '9mobile-sme-data-1gb'), ('N1500 7GB - 7 days', '9mobile-sme-data-10gb'), ('N150 200MB - 1 day', '9mobile-sme-data-200mb')], max_length=100),
        ),
        migrations.AlterField(
            model_name='glodatatopup',
            name='plan',
            field=models.CharField(choices=[('N100 105MB - 2 days', 'glo-daily-100'), ('N200 350MB - 4 days', 'glo-2days-200'), ('N500 1.05GB - 14 days', 'glo-special-500'), ('N1000 2.5GB - 30 days', 'glo-monthly-1000'), ('N2000 5.8GB - 30 days', 'glo-monthly-2000'), ('N2500 7.7GB - 30 days', 'glo-monthly-2500'), ('N3000 10GB - 30 days', 'glo-monthly-3000'), ('N4000 13.25GB - 30 days', 'glo-monthly-4000'), ('N5000 18.25GB - 30 days', 'glo-monthly-5000'), ('N8000 29.5GB - 30 days', 'glo-monthly-8000'), ('N10000 50GB - 30 days', 'glo-monthly-10000'), ('N15000 93GB - 30 days', 'glo-15000-30days'), ('N18000 119GB - 30 days', 'glo-20000-30days'), ('N1500 4.1GB - 30 days', 'glo-monthly-1500'), ('N20000 138GB - 30 days', 'glo-20000-30days'), ('N70 200MB SME - 14 days', 'glo-dg-99'), ('N320 1GB SME - 30 days', 'glo-dg-295'), ('N960 3GB SME - 30 days', 'glo-dg-890'), ('N3100 10GB SME - 30 days', 'glo-dg-4950'), ('N640 2GB SME - 30 days', 'glo-dg-495'), ('N160 500MB SME - 14 days', 'glo-dg-250'), ('N1600 5GB SME - 30 days', 'glo-dg-2475'), ('N50 45MB + 5MB Night - 1 day', 'glo-daily-50'), ('N100 115MB + 35MB Night - 1 day', 'glo-campus-booster-100'), ('N200 240MB + 110MB Night - 2 days', 'glo-campus-booster-200'), ('N500 800MB + 1GB Night - 2 weeks', 'glo-campus-booster-500'), ('N1000 1.9GB + 2GB Night - 30 days', 'glo-campus-booster-1000'), ('N1500 3.5GB + 4GB Night - 30 days', 'glo-special-1500'), ('N2000 5.2GB + 4GB Night - 30 days', 'glo-campus-booster-2000'), ('N2500 6.8GB + 4GB Night - 30 days', 'glo-2000-7days'), ('N3000 10GB + 4GB Night - 30 days', 'glo-monthly-3000'), ('N4000 14GB + 4GB Night - 30 days', 'glo-monthly-4000'), ('N5000 20GB + 4GB Night - 30 days', 'glo-campus-booster-5000'), ('N8000 27.5GB + 2GB Night - 30 days', 'glo-monthly-8000'), ('N10000 46GB + 4GB Night - 30 days', 'glo-monthly-10000'), ('N15000 86GB + 7GB Night - 30 days', 'glo-15000-30days'), ('N18000 109GB + 10GB Night - 30 days', 'glo-20000-30days'), ('N20000 126GB + 12GB Night - 30 days', 'glo-20000-30days'), ('N300 1GB Special', 'glo-social-oneoff-300'), ('N500 2GB Special', 'glo-special-500')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mtndatatopup',
            name='plan',
            field=models.CharField(choices=[('N100 100MB - 24 hrs', 'mtn-10mb-100'), ('N200 200MB - 2 days', 'mtn-230mb-200'), ('N1000 1.5GB - 30 days', 'mtn-1500mb-1000'), ('N2000 4.5GB - 30 days', 'mtn-2.7gb-2000'), ('N1500 6GB - 7 days', 'mtn-3.5gb-1500'), ('N2500 6GB - 30 days', 'mtn-3.5gb-2500'), ('N3000 8GB - 30 days', 'mtn-6.75gb-3000'), ('N3500 10GB - 30 days', 'mtn-5.5gb-3500'), ('N5000 15GB - 30 days', 'mtn-14.5gb-5000'), ('N6000 20GB - 30 days', 'mtn-data-6500'), ('N10000 40GB - 30 days', 'mtn-34gb-30-10000'), ('N15000 75GB - 30 days', 'mtn-75gb-20000'), ('N20000 110GB - 30 days', 'mtn-20gb-7500'), ('N1500 3GB - 30 days', 'mtn-xtra-1000'), ('N10000 25GB SME - 1 month', 'mtn-25gb-9000'), ('N50000 165GB SME - 2 months', 'mtn-165gb-35000'), ('N100000 360GB SME - 3 months', 'mtn-480gb-90000'), ('N450000 4.5TB - 1 year', 'mtn-1500gb-yearly'), ('N110000 1TB - 1 year', 'mtn-1500gb-yearly'), ('N600 2.5GB - 2 days', 'mtn-2-5gb-ex-600'), ('N22000 120GB + 80mins - 30 days', 'mtn-120gb-24000'), ('N20000 100GB - 2 months', 'mtn-150gb-40000'), ('N30000 160GB - 2 months', 'mtn-150gb-30000'), ('N50000 400GB - 3 months', 'mtn-480gb-90000'), ('N75000 600GB - 3 months', 'mtn-hynetflex-75000-90'), ('N300 Xtratalk Weekly', 'mtn-xtrabundle-500'), ('N500 Xtratalk Weekly', 'mtn-xtrabundle-500'), ('N1000 Xtratalk Monthly', 'mtn-xtra-1000'), ('N2000 Xtratalk Monthly', 'mtn-2.7gb-2000'), ('N5000 Xtratalk Monthly', 'mtn-14.5gb-5000'), ('N10000 Xtratalk Monthly', 'mtn-34gb-30-10000'), ('N15000 Xtratalk Monthly', 'mtn-75gb-20000'), ('N20000 Xtratalk Monthly', 'mtn-20gb-7500'), ('N800 3GB - 2 days', 'mtn-3.2gb-1000'), ('N2000 7GB - 7 days', 'mtn-7gb-3000'), ('N200 Xtradata', 'mtn-230mb-200')], max_length=50),
        ),
    ]
