# Generated by Django 5.2.6 on 2026-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_airteldatatopup_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricitypaymentcustomer",
            name="meter_number",
            field=models.IntegerField(),
        ),
    ]
