# Generated by Django 5.2.6 on 2026-01-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_electricitypaymentcustomer_meter_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electricitypayment",
            name="phone_number",
        ),
    ]
