# Generated by Django 5.2.6 on 2026-08-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_airteldatatopup_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dstvpayment',
            name='dstv_plan',
            field=models.CharField(choices=[('DStv  Compact + Showmax N21,250', 'dstv-compact-showmax'), ('DStv  Compact N19,000', 'dstv79'), ('DStv Asia + Showmax N19,400', 'dstv-asia-showmax'), ('DStv Compact + Extra View N25,000', 'dstv30'), ('DStv Compact + French Plus N43,500', 'dstv47'), ('DStv Compact + French Touch + ExtraView N32,000', 'com-frenchtouch-extra'), ('DStv Compact + French Touch N26,000', 'com-frenchtouch'), ('DStv Compact Plus + Extra View N36,000', 'dstv45'), ('DStv Compact Plus + French Plus N54,500', 'dstv43'), ('DStv Compact Plus + French Touch N37,000', 'complus-frenchtouch'), ('DStv Compact Plus + FrenchPlus + Extra View N60,500', 'complus-french-extraview'), ('DStv Compact Plus + Showmax N32,250', 'dstv-compact-plus-showmax'), ('DStv Compact Plus Movie Bundle Add-on E36 - N3,500', 'dstv-compact-plus-movie'), ('DStv Compact Plus N30,000', 'dstv7'), ('DStv Confam + ExtraView N17,000', 'confam-extra'), ('DStv French 11 N10,800', 'french11'), ('DStv French Plus Add-on N24,500', 'frenchplus-addon'), ('DStv French Touch Add-on N7,000', 'frenchtouch-addon'), ('DStv Great Wall Standalone Bouquet + Showmax N8,300', 'dstv-greatwall-showmax'), ('DStv Great Wall Standalone Bouquet N3,800', 'dstv-greatwall'), ('DStv India Add-on N14,900', 'dstv-indian-add-on'), ('DStv Indian N14,900', 'dstv-indian'), ('DStv Movie Bundle Add-on N3500', 'dstv-movie-bundle-add-on'), ('DStv Padi + ExtraView N10,400', 'padi-extra'), ('DStv Padi + Showmax N8,900', 'dstv-padi-showmax'), ('DStv Padi N4,400', 'dstv-padi'), ('DStv Premium + Extra View N50,500', 'dstv33'), ('DStv Premium + French + Extra View N75,000', 'dstv62'), ('DStv Premium + French + Showmax N69,000', 'dstv-premium-french-showmax'), ('DStv Premium + Showmax N44,500', 'dstv-premium-showmax'), ('DStv Premium N44,500', 'dstv3'), ('DStv Premium W/Afr + Showmax N50,500', 'dstv-premium-wafr-showmax'), ('DStv Premium-Asia N50,500', 'dstv10'), ('DStv Premium-French N69,000', 'dstv9'), ('DStv Showmax Premier League Add-on N3,600', 'dstv-showmax-premier-league'), ('DStv Yanga + ExtraView N12,000', 'yanga-extra'), ('DStv Yanga + Showmax N8,250', 'dstv-yanga-showmax'), ('DStv Yanga N6,000', 'dstv-yanga'), ('Dstv Confam + Showmax N13,250', 'dstv-confam-showmax'), ('Dstv Confam N11,000', 'dstv-confam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gotvpayment',
            name='gotv_plan',
            field=models.CharField(choices=[('GOtv Jinja N3,900', 'gotv-jinja'), ('GOtv Jolli N5,800', 'gotv-jolli'), ('GOtv Max N8,500', 'gotv-max'), ('GOtv Smallie - monthly N1900', 'gotv-smallie'), ('GOtv Smallie - quarterly N5,100', 'gotv-smallie-3months'), ('GOtv Smallie - yearly N15,000', 'gotv-smallie-1year'), ('GOtv Supa - monthly N11,400', 'gotv-supa'), ('GOtv Supa Plus - monthly N16,800', 'gotv-supa-plus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startimespayment',
            name='startimes_plan',
            field=models.CharField(choices=[('Basic (Antenna) - 1400 Naira - 1 Week', 'basic-weekly'), ('Basic (Antenna) - 4,000 Naira - 1 Month', 'basic'), ('Basic (Dish) - 1,700 Naira - 1 Week', 'smart-weekly'), ('Basic (Dish) - 5,100 Naira - 1 Month', 'smart'), ('Chinese (Dish) - 21,000 Naira - 1 month', 'uni-1'), ('Classic (Antenna) - 2000 Naira - 1 Week', 'classic-weekly'), ('Classic (Antenna) - 6000 Naira - 1 Month', 'classic'), ('Classic (Dish) - 2300 Naira - 1 Week', 'special-weekly'), ('Classic (Dish) - 2500 Naira - 1 Week', 'classic-weekly-dish'), ('Classic (Dish) - 7400 Naira - 1 Month', 'special-monthly'), ('Global (Dish) - 21000 Naira - 1 Month', 'global-monthly-dish'), ('Global (Dish) - 7000 Naira - 1Week', 'global-weekly-dish'), ('Nova (Antenna) - 2,100 Naira - 1 Month', 'uni-2'), ('Nova (Antenna) - 700 Naira - 1 Week', 'nova-weekly'), ('Nova (Dish) - 2100 Naira - 1 Month', 'nova'), ('Nova (Dish) - 700 Naira - 1 Week', 'nova-dish-weekly'), ('Startimes SHS - 12,000 Naira - Monthly', 'shs-monthly-12000'), ('Startimes SHS - 19,800 Naira - Monthly', 'shs-monthly-19800'), ('Startimes SHS - 2,800 Naira - Weekly', 'shs-weekly-2800'), ('Startimes SHS - 21,000 Naira - Monthly', 'shs-monthly-21000'), ('Startimes SHS - 39,000 Naira - Monthly', 'shs-monthly-39000'), ('Startimes SHS - 4,620 Naira - Weekly', 'shs-weekly-4620'), ('Startimes SHS - 4,900 Naira - Weekly', 'shs-weekly-4900'), ('Startimes SHS - 9,100 Naira - Weekly', 'shs-weekly-9100'), ('Super (Antenna) - 3,200 Naira - 1 Week', 'super-antenna-weekly'), ('Super (Antenna) - 9,500 Naira - 1 Month', 'super-antenna-monthly'), ('Super (Dish) - 3,300 Naira - 1 Week', 'super-weekly'), ('Super (Dish) - 9,800 Naira - 1 Month', 'super')], max_length=100),
        ),
    ]
