# Generated by Django 5.2.6 on 2026-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_dstvpayment_dstv_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airteldatatopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='airteldatatopup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='airteldatatopup',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airtime2cash',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='airtime2cash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='airtime2cash',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dstvpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dstvpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dstvpayment',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electricitypayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='electricitypayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='electricitypayment',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etisalatdatatopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='etisalatdatatopup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='etisalatdatatopup',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glodatatopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='glodatatopup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='glodatatopup',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gotvpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='gotvpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gotvpayment',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jambregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jambregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jambregistration',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mtndatatopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mtndatatopup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mtndatatopup',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showmaxpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='showmaxpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='showmaxpayment',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startimespayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='startimespayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='startimespayment',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waecregitration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='waecregitration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='waecregitration',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waecresultchecker',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='waecresultchecker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='waecresultchecker',
            name='vtpass_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VTpassWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('vt_status', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id', 'vt_status'], name='payments_vt_request_5680cb_idx')],
                'unique_together': {('request_id', 'transaction_id', 'vt_status')},
            },
        ),
    ]
