# Generated by Django 5.2.6 on 2026-09-01 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_payment', '0010_alter_group_service_type'),
        ('payments', '0010_add_vtpass_status_and_webhook_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='grouppayment',
            name='payment_type',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('dstv', 'DSTV'), ('gotv', 'GOTV'), ('startimes', 'Startimes'), ('showmax', 'ShowMax')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='grouppayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='grouppayment',
            name='vtu_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='grouppayment',
            index=models.Index(fields=['group', '-created_at'], name='payments_gr_group_i_2806e5_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppayment',
            index=models.Index(fields=['status', '-created_at'], name='payments_gr_status_e9843c_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppayment',
            index=models.Index(fields=['vtu_reference'], name='payments_gr_vtu_ref_be3501_idx'),
        ),
    ]
