# Generated by Django 5.2.6 on 2026-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_group_payment_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
