# Generated by Django 5.2.6 on 2026-09-30 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_withdrawal_recipient_code_withdrawal_transfer_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recepiant_dva_account_number', models.CharField(blank=True, max_length=10)),
                ('recepiant_email', models.CharField(blank=True, max_length=100)),
                ('recepiant_full_name', models.CharField(blank=True, max_length=100)),
                ('transfer_method', models.CharField(choices=[('email', 'Email'), ('dva', 'DVA')], default='email', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('successful', 'Successful')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
