# Generated by Django 5.2.6 on 2026-10-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_internaltransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='airteldatatopup',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airtime2cash',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airtimetopup',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dstvpayment',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='electricitypayment',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='etisalatdatatopup',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='glodatatopup',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gotvpayment',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grouppayment',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jambregistration',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mtndatatopup',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='showmaxpayment',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startimespayment',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='waecregitration',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='waecresultchecker',
            name='vtpass_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
