# Generated by Django 5.2.6 on 2026-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_airteldatatopup_vtpass_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='provider',
            field=models.CharField(db_index=True, default='paystack', max_length=20),
        ),
    ]
