# Generated by Django 5.2.6 on 2025-11-17 21:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('points_cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator])),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory', models.IntegerField(blank=True, default=0, null=True)),
                ('availability_start', models.DateTimeField(auto_now=True)),
                ('availability_end', models.DateTimeField(auto_now=True)),
                ('fulfilment_type', models.CharField(choices=[('sms', 'SMS Delivery'), ('email', 'Email Delivery'), ('manual', 'Manual Fulfilment'), ('instant', 'Instant Delivery')], default='instant', max_length=20)),
                ('polarity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedemptionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_deducted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(auto_now=True, null=True)),
                ('fulfilment_payload', models.JSONField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_user', to=settings.AUTH_USER_MODEL)),
                ('reward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_reward', to='loyalty_market.reward')),
            ],
        ),
    ]
