# Generated by Django 5.2.6 on 2026-01-31 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='points_cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
