# Generated by Django 5.2.6 on 2026-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_market', '0002_alter_reward_points_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='availability_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='availability_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
