# Generated by Django 5.2.6 on 2026-08-11 19:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_place', '0009_remove_eventwithdrawal_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_name', models.CharField(help_text='Unique affiliate name (letters and numbers only)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Affiliate name can only contain letters and numbers.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Commission percentage of ticket sales', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Commission percentage snapshot for this link', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='market_place.eventinfo')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='affiliate.affiliateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('affiliate', 'event')},
            },
        ),
        migrations.CreateModel(
            name='AffiliateSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_count', models.IntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('payable', 'Payable'), ('paid', 'Paid'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payable_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='affiliate.affiliateprofile')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_sales', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_sales', to='market_place.eventinfo')),
                ('issued_ticket', models.ForeignKey(blank=True, help_text='First ticket of the attributed purchase (for refund tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_sale', to='market_place.issuedticket')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='affiliate.affiliatelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
