# Generated by Django 5.2.6 on 2026-08-12 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateprofile',
            name='affiliate_name',
            field=models.CharField(help_text='Unique affiliate name (letters and numbers only)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Affiliate name can only contain letters and numbers.')]),
        ),
    ]
