# Generated by Django 5.2.6 on 2026-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
