# Generated by Django 5.2.6 on 2026-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_alter_broadcast_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='kind',
            field=models.CharField(choices=[('new_month', 'New Month'), ('important', 'Important'), ('announcement', 'Announcement')], db_index=True, max_length=20),
        ),
    ]
