# Generated by Django 5.2.6 on 2025-11-17 21:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('50.00'))])),
                ('phone_number', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField()),
                ('repeat_days', models.IntegerField(default=0, help_text='0 for one-time, >0 for recurring every N days')),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('failed_runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoTopUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('vtu_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('vtu_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('auto_topup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='autotopup.autotopup')),
            ],
            options={
                'verbose_name_plural': 'Auto Top-Up Histories',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='autotopup',
            index=models.Index(fields=['user', 'is_active'], name='autotopup_a_user_id_5cc76f_idx'),
        ),
        migrations.AddIndex(
            model_name='autotopup',
            index=models.Index(fields=['next_run', 'is_active'], name='autotopup_a_next_ru_897100_idx'),
        ),
    ]
