import logging
from decimal import Decimal

from django.shortcuts import get_object_or_404
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import extend_schema
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from market_place.models import EventInfo

from .models import AffiliateLink, AffiliateProfile, AffiliateSale
from .serializers import (
    AffiliateApplySerializer,
    AffiliateDashboardSerializer,
    AffiliateLinkSerializer,
    AffiliateSaleSerializer,
    AffiliateStatusSerializer,
)
from .utils import pay_out, record_attribution, sweep_payable

logger = logging.getLogger(__name__)

TAG = ["Affiliate"]


def get_profile_or_404(user):
    return get_object_or_404(AffiliateProfile, user=user)


class ApplyAffiliateView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="Apply to become an affiliate",
        description=(
            "Submit an affiliate application. affiliate_name must contain only "
            "letters and numbers and be unique. agreement must be true."
        ),
        request=AffiliateApplySerializer,
        responses={201: AffiliateStatusSerializer, 400: OpenApiTypes.OBJECT},
        tags=TAG,
    )
    def post(self, request):
        serializer = AffiliateApplySerializer(
            data=request.data, context={"request": request}
        )
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        data = serializer.validated_data
        affiliate, created = AffiliateProfile.objects.update_or_create(
            user=request.user,
            defaults={
                "affiliate_name": data["affiliate_name"],
                "facebook": data.get("facebook") or None,
                "instagram": data.get("instagram") or None,
                "twitter": data.get("twitter") or None,
                "tiktok": data.get("tiktok") or None,
                "agreement_accepted": data["agreement"],
            },
        )
        if created or affiliate.status == "rejected":
            affiliate.status = "pending"
            affiliate.save(update_fields=["status"])

        return Response(
            AffiliateStatusSerializer(affiliate).data,
            status=status.HTTP_201_CREATED,
        )


class AffiliateStatusView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="Get my affiliate status",
        description="Return the affiliate application status and settings for the authenticated user",
        request=None,
        responses={200: AffiliateStatusSerializer, 404: OpenApiTypes.OBJECT},
        tags=TAG,
    )
    def get(self, request):
        profile = get_profile_or_404(request.user)
        return Response(
            AffiliateStatusSerializer(profile).data, status=status.HTTP_200_OK
        )


class AffiliateLinkView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="List my affiliate links",
        description="List all affiliate links generated by the authenticated user",
        request=None,
        responses={200: AffiliateLinkSerializer(many=True), 404: OpenApiTypes.OBJECT},
        tags=TAG,
    )
    def get(self, request):
        profile = get_profile_or_404(request.user)
        links = AffiliateLink.objects.filter(affiliate=profile)
        return Response(
            AffiliateLinkSerializer(links, many=True).data, status=status.HTTP_200_OK
        )

    @extend_schema(
        summary="Generate an affiliate link for an event",
        description=(
            "Create a shareable link for an approved event. Requires an approved "
            "affiliate profile. The link is built from the event id and affiliate name."
        ),
        request=OpenApiTypes.OBJECT,
        responses={
            200: AffiliateLinkSerializer,
            400: OpenApiTypes.OBJECT,
            403: OpenApiTypes.OBJECT,
            404: OpenApiTypes.OBJECT,
        },
        tags=TAG,
    )
    def post(self, request):
        profile = get_profile_or_404(request.user)
        if not profile.is_approved:
            return Response(
                {"error": "Your affiliate application has not been approved yet."},
                status=status.HTTP_403_FORBIDDEN,
            )

        event_id = request.data.get("event_id")
        if not event_id:
            return Response(
                {"error": "event_id is required"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        event = get_object_or_404(EventInfo, id=event_id)
        if not event.is_approved:
            return Response(
                {"error": "This event is not yet approved for ticket sales"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        link, created = AffiliateLink.objects.get_or_create(
            affiliate=profile,
            event=event,
            defaults={"commission_rate": profile.commission_rate},
        )
        data = AffiliateLinkSerializer(link).data
        data["created"] = created
        return Response(data, status=status.HTTP_200_OK)


class AffiliateAttributionView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="Record affiliate link attribution",
        description=(
            "Record that the authenticated user opened an event via an affiliate "
            "link. The sale stays pending until the user purchases a ticket, at "
            "which point it becomes success and commission is recorded."
        ),
        request=OpenApiTypes.OBJECT,
        responses={
            200: OpenApiTypes.OBJECT,
            400: OpenApiTypes.OBJECT,
            404: OpenApiTypes.OBJECT,
        },
        tags=TAG,
    )
    def post(self, request):
        event_id = request.data.get("event_id")
        affiliate_name = request.data.get("affiliate_username")
        if not event_id or not affiliate_name:
            return Response(
                {"error": "event_id and affiliate_username are required"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        event = get_object_or_404(EventInfo, id=event_id)
        sale = record_attribution(
            buyer=request.user, event=event, affiliate_name=affiliate_name
        )
        if sale is None:
            return Response(
                {"error": "Invalid or inactive affiliate link for this event"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(
            {
                "success": True,
                "status": sale.status,
                "event_id": str(event.id),
                "affiliate_username": affiliate_name,
                "message": (
                    "You will be attributed to this affiliate when you purchase tickets."
                    if sale.status == "pending"
                    else "This event is already attributed."
                ),
            },
            status=status.HTTP_200_OK,
        )


class AffiliateDashboardView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="Get affiliate dashboard",
        description=(
            "Return click totals and commission amounts grouped by status. "
            "Runs the payable sweep before computing totals."
        ),
        request=None,
        responses={200: AffiliateDashboardSerializer, 404: OpenApiTypes.OBJECT},
        tags=TAG,
    )
    def get(self, request):
        profile = get_profile_or_404(request.user)
        sweep_payable(profile)

        sales = AffiliateSale.objects.filter(affiliate=profile)
        links = AffiliateLink.objects.filter(affiliate=profile)

        total_clicks = sum(link.clicks for link in links)
        sums = {s: Decimal("0.00") for s in ("pending", "success", "payable", "paid")}
        for sale in sales:
            sums[sale.status] += sale.commission_amount

        data = {
            "total_clicks": total_clicks,
            "total_sales": sales.count(),
            "pending_count": sales.filter(status="pending").count(),
            "success_count": sales.filter(status="success").count(),
            "payable_count": sales.filter(status="payable").count(),
            "paid_count": sales.filter(status="paid").count(),
            "revoked_count": sales.filter(status="revoked").count(),
            "pending_amount": sums["pending"],
            "payable_amount": sums["payable"],
            "paid_amount": sums["paid"],
        }
        return Response(data, status=status.HTTP_200_OK)


class AffiliateSalesListView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="List my affiliate commissions",
        description=(
            "List commission records for the authenticated affiliate. "
            "Runs the payable sweep before returning."
        ),
        request=None,
        responses={200: AffiliateSaleSerializer(many=True), 404: OpenApiTypes.OBJECT},
        tags=TAG,
    )
    def get(self, request):
        profile = get_profile_or_404(request.user)
        sweep_payable(profile)
        sales = AffiliateSale.objects.filter(affiliate=profile)
        return Response(
            AffiliateSaleSerializer(sales, many=True).data,
            status=status.HTTP_200_OK,
        )


class AffiliatePayoutView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        summary="Request affiliate payout",
        description=(
            "Credit all payable commissions to the authenticated affiliate's wallet. "
            "Runs the payable sweep first."
        ),
        request=None,
        responses={
            200: OpenApiTypes.OBJECT,
            400: OpenApiTypes.OBJECT,
            403: OpenApiTypes.OBJECT,
            404: OpenApiTypes.OBJECT,
        },
        tags=TAG,
    )
    def post(self, request):
        profile = get_profile_or_404(request.user)
        if not profile.is_approved:
            return Response(
                {"error": "Your affiliate application has not been approved yet."},
                status=status.HTTP_403_FORBIDDEN,
            )

        paid, total, reference = pay_out(profile)
        if total <= 0:
            return Response(
                {
                    "message": "No payable commissions to pay out.",
                    "amount_paid": "0.00",
                },
                status=status.HTTP_200_OK,
            )
        return Response(
            {
                "success": True,
                "message": f"{len(paid)} commission(s) paid out.",
                "amount_paid": str(total),
                "wallet_balance": str(profile.user.wallet.balance),
                "reference": reference,
            },
            status=status.HTTP_200_OK,
        )
