# Generated by Django 5.2.6 on 2025-11-17 21:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=200)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('multiplier', 'Points Multiplier'), ('fixed_bonus', 'Fixed Bonus'), ('percentage_bonus', 'Percentage Bonus')], default='multiplier', max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=1, default=1.0, help_text='Points multiplier (e.g., 2.0 for double points)', max_digits=3)),
                ('bonus_amount', models.IntegerField(default=0, help_text='Fixed bonus points or percentage bonus')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('adjusted', 'Admin Adjustment'), ('expired', 'Expired'), ('reversed', 'Reversed')], max_length=20)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(blank=True, choices=[('vtu_purchase', 'VTU Purchase'), ('referral', 'Referral Bonus'), ('daily_login', 'Daily Login'), ('campaign', 'Campaign Bonus'), ('admin_award', 'Admin Award'), ('signup_bonus', 'Signup Bonus'), ('milestone', 'Milestone Reward')], max_length=50, null=True)),
                ('description', models.TextField(help_text='Detailed description of the transaction')),
                ('reference', models.CharField(blank=True, help_text='Related transaction reference', max_length=100, null=True)),
                ('balance_before', models.IntegerField(help_text='Points balance before transaction')),
                ('balance_after', models.IntegerField(help_text='Points balance after transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data (e.g., purchase amount, campaign info)', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who made the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_adjustments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bonus Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_earned', models.IntegerField(default=0, help_text='Total points earned over lifetime')),
                ('lifetime_redeemed', models.IntegerField(default=0, help_text='Total points redeemed over lifetime')),
                ('last_daily_login', models.DateField(blank=True, help_text='Last date user claimed daily login points', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('bonus_awarded', models.BooleanField(default=False)),
                ('first_transaction_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
