# Generated by Django 5.2.6 on 2026-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
