# Generated by Django 5.2.6 on 2026-09-17 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscampaign',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Bonus Histories'},
        ),
        migrations.AlterModelOptions(
            name='bonuspoint',
            options={'ordering': ('-points',)},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='bonuscampaign',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed bonus points or percentage bonus', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonuscampaign',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points multiplier (e.g., 2.0 for double points)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, help_text='Points balance after transaction', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, help_text='Points balance before transaction', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='lifetime_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total points earned over lifetime', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='lifetime_redeemed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total points redeemed over lifetime', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonuspoint',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
