# Generated by Django 5.2.6 on 2025-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin_is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='transaction_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
