# Generated by Django 5.2.6 on 2025-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_pin_is_set_profile_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
