# Generated by Django 5.2.6 on 2026-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(default="B9D3BD", max_length=6),
        ),
    ]
