# Generated by Django 5.2.6 on 2026-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(default="3B8D6B", max_length=6),
        ),
    ]
