# Generated by Django 5.2.6 on 2026-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(default="677D7C", max_length=6),
        ),
    ]
