# Generated by Django 5.2.6 on 2026-04-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_profile_referral_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="referral_code",
        ),
    ]
