# Generated by Django 5.2.6 on 2026-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_profile_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(default="C2498A", max_length=6),
        ),
    ]
