# Generated by Django 5.2.6 on 2026-05-09 08:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=accounts.models.generate_referal_code, max_length=6, unique=True),
        ),
    ]
