# Generated by Django 5.2.6 on 2026-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
