# Generated by Django 5.2.6 on 2026-09-01 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_pin_failed_attempts_profile_pin_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_DVA',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='PaystackDedicatedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedicated_account_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('account_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(default='Wema Bank', max_length=50)),
                ('bank_slug', models.CharField(default='wema-bank', max_length=50)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('customer_code', models.CharField(db_index=True, max_length=50)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bvn_encrypted', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('paystack_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dva_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['account_number'], name='accounts_pa_account_0b1e46_idx'), models.Index(fields=['customer_code'], name='accounts_pa_custome_781d9c_idx'), models.Index(fields=['user'], name='accounts_pa_user_id_fb8844_idx')],
            },
        ),
    ]
