# Generated by Django 5.2.6 on 2026-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_has_dva_and_paystack_dva'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackdedicatedaccount',
            name='dva_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paystackdedicatedaccount',
            name='dva_account_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
