# Generated by Django 5.2.6 on 2026-10-09 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_paystackdedicatedaccount_dva_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombaDedicatedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('account_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('nomba_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nomba_dva_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['account_number'], name='accounts_no_account_0e29b4_idx'), models.Index(fields=['account_ref'], name='accounts_no_account_b5986b_idx'), models.Index(fields=['user'], name='accounts_no_user_id_729258_idx')],
            },
        ),
    ]
