# Generated by Django 5.2.6 on 2026-08-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preference', '0002_updateusermodel_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='updateusermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
