# Generated by Django 5.2.6 on 2026-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preference', '0003_updateusermodel_gender_updateusermodel_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateusermodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='updateusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, null=True),
        ),
    ]
