# Generated by Django 5.2.6 on 2026-09-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
    ]
