# Generated by Django 5.2.6 on 2026-09-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ('-created_at',)},
        ),
    ]
