# Generated by Django 5.2.6 on 2026-08-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
