# Generated by Django 5.2.6 on 2026-09-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_delete_withdraw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ('-created_at',)},
        ),
    ]
