# Generated by Django 5.2.6 on 2025-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_accountname_withdraw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="account_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="bank_code",
            field=models.CharField(max_length=10),
        ),
    ]
