# Generated by Django 5.2.6 on 2025-12-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_withdraw_bank_name_withdraw_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdraw",
            name="user",
        ),
    ]
