# Generated by Django 5.2.6 on 2026-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
