# Generated by Django 5.2.6 on 2026-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="invite_members",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="group",
            name="plan",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="group",
            name="plan_type",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="service_type",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="group",
            name="sub_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="group",
            name="target_amount",
            field=models.IntegerField(default=0),
        ),
    ]
