# Generated by Django 5.2.6 on 2026-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "group_payment",
            "0002_group_invite_members_group_plan_group_plan_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="join_code",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")],
                default="active",
                max_length=10,
            ),
        ),
    ]
