# Generated by Django 5.2.6 on 2026-02-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_payment", "0003_group_join_code_group_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="status",
        ),
        migrations.AddField(
            model_name="group",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
