# Generated by Django 5.2.6 on 2026-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_payment", "0006_group_join_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("airtime", "Airtime"),
                    ("data", "Data"),
                    ("lightbill", "Light Bill"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
