# Generated by Django 5.2.6 on 2026-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_payment", "0007_alter_group_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="plan",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="group",
            name="sub_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
