# Generated by Django 5.2.6 on 2026-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_payment", "0008_update_group_nullable_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="deadline",
        ),
        migrations.AlterField(
            model_name="group",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("airtime", "Airtime"),
                    ("data", "Data"),
                    ("lightbill", "Light Bill"),
                    ("gotv", "GOTV"),
                    ("dstv", "DSTV"),
                    ("showmax", "Showmax"),
                    ("startimes", "StarTimes"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("member", "Member")],
                default="member",
                max_length=20,
            ),
        ),
    ]
