# Generated by Django 5.2.6 on 2026-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "group_payment",
            "0009_remove_group_deadline_alter_group_service_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("airtime", "Airtime"),
                    ("data", "Data"),
                    ("electricity", "Electricity"),
                    ("gotv", "GOTV"),
                    ("dstv", "DSTV"),
                    ("showmax", "Showmax"),
                    ("startimes", "StarTimes"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
