from celery.schedules import crontab

"""
Django settings for bluesea_mobile project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv
from datetime import timedelta

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = "accounts.Profile"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

# CSRF and CORS
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]


# Application definition

JAZZMIN_SETTINGS = {
    "site_title": "BlueSea Admin",
    "site_header": "BlueseaMobile",
    "site_brand": "BlueseaMobile",
    "site_logo": None,
    "site_icon": None,
    "welcome_sign": "Welcome to the BlueSea Admin Portal",
    "copyright": "BlueSea Mobile Technologies",
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Users", "model": "accounts.Profile"},
        {"name": "Transactions", "model": "transactions.WalletTransaction"},
        {"name": "Events", "model": "market_place.EventInfo"},
        {"name": "Wallets", "model": "wallet.Wallet"},
        {"name": "Logout", "url": "admin:logout"},
    ],
    "usermenu_links": [
        {
            "name": "My Profile",
            "url": "/admin/accounts/profile/",
            "icon": "fas fa-user",
        },
        {"name": "Logout", "url": "admin:logout", "icon": "fas fa-sign-out-alt"},
    ],
    "show_avatar": True,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "accounts",
        "wallet",
        "transactions",
        "payments",
        "market_place",
        "group_payment",
        "bonus",
        "loyalty_market",
        "notifications",
        "autotopup",
        "user_preference",
        "support",
        "auth",
        "django_celery_beat",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.group": "fas fa-layer-group",
        "accounts.Profile": "fas fa-user-circle",
        "accounts.EmailVerification": "fas fa-envelope-open-text",
        "accounts.ResetPassword": "fas fa-key",
        "wallet.Wallet": "fas fa-wallet",
        "transactions.WalletTransaction": "fas fa-exchange-alt",
        "transactions.FundWallet": "fas fa-arrow-circle-down",
        "transactions.Withdraw": "fas fa-arrow-circle-up",
        "transactions.AccountName": "fas fa-university",
        "payments.AirtimeTopUp": "fas fa-phone",
        "payments.MTNDataTopUp": "fas fa-wifi",
        "payments.AirtelDataTopUp": "fas fa-wifi",
        "payments.GloDataTopUp": "fas fa-wifi",
        "payments.EtisalatDataTopUp": "fas fa-wifi",
        "payments.DSTVPayment": "fas fa-tv",
        "payments.GOTVPayment": "fas fa-tv",
        "payments.StartimesPayment": "fas fa-tv",
        "payments.ElectricityPayment": "fas fa-bolt",
        "payments.WAECRegitration": "fas fa-graduation-cap",
        "payments.WAECResultChecker": "fas fa-graduation-cap",
        "payments.JAMBRegistration": "fas fa-graduation-cap",
        "payments.Airtime2Cash": "fas fa-money-bill-wave",
        "market_place.TicketVendor": "fas fa-store",
        "market_place.VendorKYC": "fas fa-id-card",
        "market_place.EventInfo": "fas fa-calendar-alt",
        "market_place.TicketType": "fas fa-ticket-alt",
        "market_place.IssuedTicket": "fas fa-qrcode",
        "market_place.EventScanner": "fas fa-barcode",
        "group_payment.Group": "fas fa-users",
        "group_payment.GroupMember": "fas fa-user-friends",
        "bonus.BonusPoint": "fas fa-coins",
        "bonus.BonusHistory": "fas fa-history",
        "bonus.BonusCampaign": "fas fa-bullhorn",
        "bonus.Referral": "fas fa-handshake",
        "loyalty_market.Reward": "fas fa-gift",
        "loyalty_market.RedemptionTransaction": "fas fa-receipt",
        "notifications.Notification": "fas fa-bell",
        "autotopup.AutoTopUp": "fas fa-sync-alt",
        "autotopup.AutoTopUpHistory": "fas fa-clock",
        "django_celery_beat.PeriodicTask": "fas fa-tasks",
        "django_celery_beat.CrontabSchedule": "fas fa-calendar-check",
        "django_celery_beat.IntervalSchedule": "fas fa-stopwatch",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

INSTALLED_APPS = [
    "jazzmin",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "debug_toolbar",
    "django_celery_beat",
    # rest framework
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "channels",
    "anymail",
    # local apps
    "accounts",
    "wallet",
    "transactions",
    "payments",
    "market_place",
    "group_payment",
    "notifications",
    "user_preference",
    "bonus",
    "autotopup",
    "loyalty_market",
    "support",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "100/day",
        "scanner": "20/min",  # For ticket scanning
    },
}


ROOT_URLCONF = "bluesea_mobile.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = 'bluesea_mobile.wsgi.application'
ASGI_APPLICATION = "bluesea_mobile.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#         'CONN_MAX_AGE': 600,
#     }
#}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DATABASE_NAME"),
        "USER": os.environ.get("DATABASE_USER"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
        "HOST": os.environ.get("DATABASE_HOST"),
        "PORT": os.environ.get("DATABASE_PORT"),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {"connect_timeout": 10, "options": "-c statement_timeout=30000"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

LOCAL_URL = os.environ.get("LOCAL_URL")

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_HOST_USER", "noreply@bluesea.com")
FROM_EMAIL = EMAIL_HOST_USER
# FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')


PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY = os.environ.get("PAYSTACK_PUBLIC_KEY")


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "debug.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "transactions": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}


# Set to True only if you are okay with ANY domain accessing your backend
# (not recommended for production).

CORS_ALLOW_ALL_ORIGINS = False

# Use the specific URL/port of your frontend development server
CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")

# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Lagos"

# Cache Configuration with fallback
REDIS_LOCATION = os.environ.get("REDIS_LOCATION")


if REDIS_LOCATION:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_LOCATION,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "bluesea",
            "TIMEOUT": 300,
        }
    }
else:
    # Fallback to local memory cache if Redis not configured
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Session Configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")
APPLE_CLIENT_ID = os.environ.get("APPLE_CLIENT_ID")

VTPASS_BASE_URL = os.environ.get("VTPASS_BASE_URL")
VTPASS_API_KEY = os.environ.get("VTPASS_API_KEY")
VTPASS_SECRET_KEY = os.environ.get("VTPASS_SECRET_KEY")
VTPASS_PUBLIC_KEY = os.environ.get("VTPASS_PUBLIC_KEY")


ANYMAIL = {
    "BREVO_API_KEY": os.environ.get("BREVO_API_KEY"),
}
PAYSTACK_PIN = os.environ.get("PAYSTACK_PIN")

TIME_ZONE = "Africa/Lagos"
