//! Admin models for `payments`. Generated from the live Postgres schema.
use super::{ColType, ModelDef, PkType};

pub fn register(out: &mut Vec<ModelDef>) {
    out.push(ModelDef {
        name: "payments.AirtelDataTopUp",
        label: "Airtel Data Top Up",
        table: "payments_airteldatatopup",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("plan", ColType::Text),
        ("billersCode", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.Airtime2Cash",
        label: "Airtime 2 Cash",
        table: "payments_airtime2cash",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("amount", ColType::Int),
        ("network", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.AirtimeTopUp",
        label: "Airtime Top Up",
        table: "payments_airtimetopup",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("amount", ColType::Int),
        ("network", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.DSTVPayment",
        label: "D S T V Payment",
        table: "payments_dstvpayment",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("billersCode", ColType::Text),
        ("dstv_plan", ColType::Text),
        ("subscription_type", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.ElectricityPayment",
        label: "Electricity Payment",
        table: "payments_electricitypayment",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("billerCode", ColType::Text),
        ("amount", ColType::Int),
        ("biller_name", ColType::Text),
        ("meter_type", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["biller_name"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.ElectricityPaymentCustomers",
        label: "Electricity Payment Customers",
        table: "payments_electricitypaymentcustomers",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("biller", ColType::Text),
        ("meter_number", ColType::Text),
        ("meter_type", ColType::Text),
        ("user_id", ColType::Int),
        ],
        search: &[],
        default_order: "-id",
    });
    out.push(ModelDef {
        name: "payments.EtisalatDataTopUp",
        label: "Etisalat Data Top Up",
        table: "payments_etisalatdatatopup",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("plan", ColType::Text),
        ("billersCode", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.GloDataTopUp",
        label: "Glo Data Top Up",
        table: "payments_glodatatopup",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("plan", ColType::Text),
        ("billersCode", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.GOTVPayment",
        label: "G O T V Payment",
        table: "payments_gotvpayment",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("billersCode", ColType::Text),
        ("gotv_plan", ColType::Text),
        ("subscription_type", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.GroupPayment",
        label: "Group Payment",
        table: "payments_grouppayment",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("payment_type", ColType::Text),
        ("total_amount", ColType::Numeric),
        ("service_details", ColType::Json),
        ("status", ColType::Text),
        ("vtu_reference", ColType::Text),
        ("created_at", ColType::DateTime),
        ("updated_at", ColType::DateTime),
        ("group_id", ColType::Uuid),
        ("initiated_by_id", ColType::Int),
        ("vtpass_response", ColType::Json),
        ],
        search: &["vtu_reference"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.GroupPaymentContribution",
        label: "Group Payment Contribution",
        table: "payments_grouppaymentcontribution",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("amount", ColType::Numeric),
        ("status", ColType::Text),
        ("created_at", ColType::DateTime),
        ("group_payment_id", ColType::Int),
        ("member_id", ColType::Int),
        ],
        search: &[],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.InternalTransfer",
        label: "Internal Transfer",
        table: "payments_internaltransfer",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("reference_id", ColType::Text),
        ("amount", ColType::Numeric),
        ("recepiant_dva_account_number", ColType::Text),
        ("recepiant_email", ColType::Text),
        ("recepiant_full_name", ColType::Text),
        ("transfer_method", ColType::Text),
        ("created_at", ColType::DateTime),
        ("completed_at", ColType::DateTime),
        ("status", ColType::Text),
        ("user_id", ColType::Int),
        ],
        search: &["reference_id", "recepiant_email", "recepiant_full_name"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.JAMBRegistration",
        label: "J A M B Registration",
        table: "payments_jambregistration",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("billerCode", ColType::Text),
        ("exam_type", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.MTNDataTopUp",
        label: "M T N Data Top Up",
        table: "payments_mtndatatopup",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("plan", ColType::Text),
        ("billersCode", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.ShowMaxPayment",
        label: "Show Max Payment",
        table: "payments_showmaxpayment",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("showmax_plan", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.StartimesPayment",
        label: "Startimes Payment",
        table: "payments_startimespayment",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("billersCode", ColType::Text),
        ("startimes_plan", ColType::Text),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.VTpassWebhookLog",
        label: "V Tpass Webhook Log",
        table: "payments_vtpasswebhooklog",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("request_id", ColType::Text),
        ("transaction_id", ColType::Text),
        ("vt_status", ColType::Text),
        ("code", ColType::Text),
        ("amount", ColType::Numeric),
        ("raw_payload", ColType::Json),
        ("is_processed", ColType::Bool),
        ("error", ColType::Text),
        ("created_at", ColType::DateTime),
        ("updated_at", ColType::DateTime),
        ],
        search: &["code"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.WAECRegitration",
        label: "W A E C Regitration",
        table: "payments_waecregitration",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.WAECResultChecker",
        label: "W A E C Result Checker",
        table: "payments_waecresultchecker",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("phone_number", ColType::Text),
        ("request_id", ColType::Text),
        ("created_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("status", ColType::Text),
        ("updated_at", ColType::DateTime),
        ("vtpass_transaction_id", ColType::Text),
        ("vtpass_response", ColType::Json),
        ],
        search: &["phone_number"],
        default_order: "-created_at",
    });
    out.push(ModelDef {
        name: "payments.Withdrawal",
        label: "Withdrawal",
        table: "payments_withdrawal",
        pk: "id",
        pk_type: PkType::Int,
        columns: &[
        ("id", ColType::Int),
        ("account_name", ColType::Text),
        ("account_number", ColType::Text),
        ("bank_code", ColType::Text),
        ("bank_name", ColType::Text),
        ("amount", ColType::Numeric),
        ("status", ColType::Text),
        ("payment_reference", ColType::Text),
        ("created_at", ColType::DateTime),
        ("completed_at", ColType::DateTime),
        ("user_id", ColType::Int),
        ("recipient_code", ColType::Text),
        ("transfer_code", ColType::Text),
        ],
        search: &["account_name", "bank_code", "bank_name", "payment_reference", "recipient_code"],
        default_order: "-created_at",
    });
}
