# Generated by Django 5.2.6 on 2026-01-31 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('hosted_by', models.CharField(help_text='Name of the host/organizer', max_length=255)),
                ('category', models.CharField(choices=[('Music', 'Music'), ('Conference', 'Conference'), ('Sports', 'Sports'), ('Networking', 'Networking')], max_length=50)),
                ('event_banner', models.ImageField(upload_to='event_banners/%Y/%m/%d/')),
                ('ticket_image', models.ImageField(blank=True, help_text='Optional ticket design image', null=True, upload_to='ticket_images/%Y/%m/%d/')),
                ('event_date', models.DateTimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('residential_address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='General Admission', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='market_place.eventinfo')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used')], default='unused', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='market_place.eventinfo')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='market_place.tickettype')),
            ],
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='market_place.ticketvendor'),
        ),
        migrations.CreateModel(
            name='VendorKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('document_image', models.FileField(help_text='Upload document (PDF, JPEG, or PNG format)', upload_to='kyc_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('proof_of_address', models.FileField(blank=True, help_text='Upload proof of address (PDF, JPEG, or PNG format)', null=True, upload_to='kyc_proof_of_address/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_kyc', to='market_place.ticketvendor')),
            ],
        ),
        migrations.CreateModel(
            name='EventScanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='market_place.eventinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
