# Generated by Django 5.2.6 on 2026-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketvendor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
