# Generated by Django 5.2.6 on 2026-01-31 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_ticketvendor_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketvendor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket Vendor', 'verbose_name_plural': 'Ticket Vendors'},
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='business_description',
            field=models.TextField(blank=True, help_text='Description of business model and typical events', null=True),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('registered', 'Registered Business'), ('organizer', 'Event Organizer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of categories: concerts, conferences, religious, sports, others', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='event_authorization',
            field=models.FileField(blank=True, help_text='Optional: Authorization letter from event owner', null=True, upload_to='vendor_event_auth/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload ID document (PDF, JPEG, or PNG format)', null=True, upload_to='vendor_ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='id_type',
            field=models.CharField(blank=True, help_text="NIN, Passport, Driver's License", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='monthly_volume',
            field=models.CharField(blank=True, help_text='Estimated monthly ticket volume range', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='proof_of_address',
            field=models.FileField(blank=True, help_text='Utility bill or bank statement within last 3 months', null=True, upload_to='vendor_proof_of_address/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketvendor',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketvendor',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketvendor',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketvendor',
            name='legal_full_name',
            field=models.CharField(blank=True, help_text='Legal full name from government ID', max_length=255, null=True),
        ),
    ]
