# Generated by Django 5.2.6 on 2026-02-11 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_place", "0003_alter_ticketvendor_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuedticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tickettype",
            options={"ordering": ["price"]},
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="qr_code_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ticket_qr_codes/"
            ),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="scanned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="transfer_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this ticket has been transferred"
            ),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="transferred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="transferred_to",
            field=models.EmailField(
                blank=True,
                help_text="Email of person this was transferred to (if any)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issuedticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional ticket tier description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="issuedticket",
            name="owner_email",
            field=models.EmailField(help_text="Current owner's email", max_length=254),
        ),
        migrations.AlterField(
            model_name="issuedticket",
            name="owner_name",
            field=models.CharField(help_text="Current owner's name", max_length=255),
        ),
        migrations.AlterField(
            model_name="issuedticket",
            name="purchased_by",
            field=models.ForeignKey(
                help_text="Original purchaser",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issuedticket",
            name="qr_code",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="issuedticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("used", "Used"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuedticket",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued_tickets",
                to="market_place.tickettype",
            ),
        ),
    ]
