# Generated by Django 5.2.6 on 2026-02-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_alter_issuedticket_options_alter_tickettype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='market_place.tickettype'),
        ),
    ]
