# Generated by Django 5.2.6 on 2026-02-07 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0005_alter_issuedticket_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedticket',
            name='owner_email',
            field=models.EmailField(help_text="Current owner's email", max_length=254),
        ),
        migrations.AlterField(
            model_name='issuedticket',
            name='owner_name',
            field=models.CharField(help_text="Current owner's name", max_length=255),
        ),
        migrations.AlterField(
            model_name='issuedticket',
            name='purchased_by',
            field=models.ForeignKey(help_text='Original purchaser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuedticket',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('used', 'Used'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuedticket',
            name='transfer_count',
            field=models.IntegerField(default=0, help_text='Number of times this ticket has been transferred'),
        ),
        migrations.AlterField(
            model_name='issuedticket',
            name='transferred_to',
            field=models.EmailField(blank=True, help_text='Email of person this was transferred to (if any)', max_length=254, null=True),
        ),
    ]
