# Generated by Django 5.2.6 on 2026-02-20 11:30 (modified to backfill slugs)

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """Generate slugs for all existing EventInfo rows."""
    EventInfo = apps.get_model('market_place', 'EventInfo')
    for event in EventInfo.objects.all():
        base_slug = slugify(event.event_title)
        short_id = str(event.id).replace('-', '')[:8]
        event.slug = f"{base_slug}-{short_id}"
        event.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0006_alter_issuedticket_owner_email_and_more'),
    ]

    operations = [
        # Add the field without unique constraint first (blank=True, no unique)
        migrations.AddField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, default=''),
            preserve_default=False,
        ),
        # Backfill slugs for existing rows
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # Now add the unique index
        migrations.AlterField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
