# Generated by Django 5.2.6 on 2026-04-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_place", "0006_eventwithdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventinfo",
            name="category",
            field=models.CharField(
                choices=[
                    ("Music", "Music"),
                    ("Conference", "Conference"),
                    ("Sports", "Sports"),
                    ("Networking", "Networking"),
                    ("Workshop", "Workshop"),
                    ("Party", "Party"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
