# Generated by Django 5.2.6 on 2026-04-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_place", "0007_alter_eventinfo_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="initial_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
