# Generated by Django 5.2.6 on 2026-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_place", "0008_tickettype_initial_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventwithdrawal",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="eventwithdrawal",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="eventwithdrawal",
            name="bank_code",
        ),
        migrations.RemoveField(
            model_name="eventwithdrawal",
            name="bank_name",
        ),
        migrations.AddField(
            model_name="eventwithdrawal",
            name="amount_credited",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="eventwithdrawal",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
