# Generated by Django 5.2.6 on 2026-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0009_remove_eventwithdrawal_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='event_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', help_text='Whether the event is in-person, virtual, or both', max_length=10),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Online meeting URL (required for online and hybrid events)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='event_location',
            field=models.CharField(blank=True, help_text='Physical venue/address (required for offline and hybrid events)', max_length=255, null=True),
        ),
    ]
