# Generated by Django 5.2.6 on 2026-09-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0010_eventinfo_event_mode_eventinfo_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinfo',
            options={'ordering': ('-event_date',)},
        ),
        migrations.AlterModelOptions(
            name='eventwithdrawal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='issuedticket',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ('price',)},
        ),
        migrations.AlterModelOptions(
            name='ticketvendor',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ticket Vendor', 'verbose_name_plural': 'Ticket Vendors'},
        ),
    ]
