# Generated by Django 5.2.6 on 2026-09-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0011_alter_eventinfo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorKYC',
        ),
    ]
