# Generated by Django 5.2.6 on 2026-09-23 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0012_delete_vendorkyc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='cancel_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='cancel_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='cancel_refunded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='cancel_status',
            field=models.CharField(default='pending', help_text='pending, processing, completed, completed_with_failures', max_length=30),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='cancel_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
