//! OpenAPI documentation. Mirrors `drf-spectacular` (`/schema/`, `/docs/`,
//! `/redoc/`): every ported endpoint is annotated with `#[utoipa::path]`
//! next to its handler and registered here.

use utoipa::{
    Modify, OpenApi,
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
};

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    info(title = "BlueSea Mobile API", version = "1.0.0"),
    modifiers(&SecurityAddon),
    tags(
        (name = "Authentication", description = "Signup, login, verification, password reset, PIN and DVA"),
        (name = "Wallet", description = "Balance and real-time updates"),
        (name = "Wallet & Transactions", description = "History, Nomba funding and DVA"),
        (name = "Payments", description = "Airtime, data, cable, electricity and exam purchases"),
        (name = "Withdrawal", description = "Bank withdrawals via Nomba"),
        (name = "User Profile", description = "Profile details and preferences"),
        (name = "Notifications", description = "In-app notifications"),
        (name = "Bonus & Rewards", description = "Points, campaigns and referrals"),
        (name = "Auto Top-Up", description = "Scheduled airtime/data purchases"),
        (name = "Loyalty Market", description = "Points redemption shop"),
        (name = "Group Payments", description = "Payment groups and membership"),
        (name = "Affiliate", description = "Event ticket referrals"),
        (name = "Support", description = "Support tickets and messages"),
        (name = "Support Admin", description = "Support ticket administration"),
        (name = "Broadcast", description = "Superuser mass notifications and email"),
        (name = "Nomba", description = "Nomba wallet funding, virtual accounts and withdrawals"),
        (name = "Marketplace Events", description = "Event creation, listing and cancellation"),
        (name = "Marketplace Tickets", description = "Ticket purchase and management"),
        (name = "Marketplace Scanner", description = "Ticket validation and scanner management"),
        (name = "Marketplace Vendors", description = "Vendor KYC and vendor tickets"),
        (name = "Marketplace Withdrawal", description = "Account verification and event earnings"),
    ),
    paths(
        crate::accounts::views::auth::sign_up,
        crate::accounts::views::auth::login,
        crate::accounts::views::auth::verify_email,
        crate::accounts::views::auth::resend_otp,
        crate::accounts::views::auth::logout,
        crate::accounts::views::auth::password_reset_request,
        crate::accounts::views::auth::password_reset_verify_otp,
        crate::accounts::views::auth::password_reset_confirm,
        crate::accounts::views::social::google_login,
        crate::accounts::views::pin::pin_set,
        crate::accounts::views::pin::pin_verify,
        crate::accounts::views::pin::pin_change,
        crate::accounts::views::pin::pin_reset_request,
        crate::accounts::views::pin::pin_reset_verify_otp,
        crate::accounts::views::pin::pin_reset_new,
        crate::accounts::views::lookup::user_lookup,
        crate::accounts::views::lookup::dva_assign,
        crate::wallet::views::balance,
        crate::transactions::views::history::history,
        crate::payments::views::airtime::airtime,
        crate::payments::views::data::mtn_data,
        crate::payments::views::data::airtel_data,
        crate::payments::views::data::glo_data,
        crate::payments::views::data::ninemobile_data,
        crate::payments::views::cable::dstv,
        crate::payments::views::cable::gotv,
        crate::payments::views::cable::startimes,
        crate::payments::views::cable::showmax,
        crate::payments::views::electricity::electricity,
        crate::payments::views::exam::waec_registration,
        crate::payments::views::exam::waec_result,
        crate::payments::views::exam::jamb_registration,
        crate::payments::views::customer::verify_customer,
        crate::accounts::kyc::status,
        crate::accounts::kyc::submit_nin,
        crate::accounts::kyc::submit_bvn,
        crate::accounts::kyc::submit_address,
        crate::accounts::kyc::upload_bill,
        crate::payments::views::betting::fund_betting,
        crate::payments::views::betting::betting_providers,
        crate::payments::views::betting::electricity_providers,
        crate::payments::views::group::create_group_payment,
        crate::payments::views::group::group_history,
        crate::payments::views::internal::internal_transfer,
        crate::payments::views::withdrawal::withdrawal,
        crate::payments::views::status::payment_status,
        crate::user_preference::views::current_user,
        crate::user_preference::views::update_user,
        crate::user_preference::views::check_user,
        crate::notifications::views::list,
        crate::notifications::views::mark_read,
        crate::notifications::views::mark_all_read,
        crate::notifications::views::delete,
        crate::bonus::views::summary,
        crate::bonus::views::history,
        crate::bonus::views::daily_login,
        crate::bonus::views::campaigns,
        crate::bonus::views::referral_list,
        crate::bonus::views::referral_apply,
        crate::autotopup::views::create,
        crate::autotopup::views::list,
        crate::autotopup::views::detail,
        crate::autotopup::views::update_full,
        crate::autotopup::views::update_partial,
        crate::autotopup::views::delete,
        crate::autotopup::views::cancel,
        crate::autotopup::views::reactivate,
        crate::autotopup::views::history,
        crate::loyalty_market::views::reward_list,
        crate::loyalty_market::views::reward_detail,
        crate::loyalty_market::views::redeem,
        crate::loyalty_market::views::redemptions,
        crate::group_payment::views::create,
        crate::group_payment::views::add_member,
        crate::group_payment::views::my_groups,
        crate::group_payment::views::details,
        crate::group_payment::views::update,
        crate::group_payment::views::join,
        crate::group_payment::views::leave,
        crate::group_payment::views::cancel,
        crate::affiliate::views::apply,
        crate::affiliate::views::status,
        crate::affiliate::views::links_list,
        crate::affiliate::views::links_create,
        crate::affiliate::views::attribution,
        crate::affiliate::views::dashboard,
        crate::affiliate::views::sales,
        crate::affiliate::views::payout,
        crate::support::views::list_tickets,
        crate::support::views::create_ticket,
        crate::support::views::ticket_detail,
        crate::support::views::add_message,
        crate::support::views::admin_list,
        crate::support::views::admin_detail,
        crate::support::views::admin_update,
        crate::support::views::admin_reply,
        crate::broadcast::views::new_month,
        crate::broadcast::views::important,
        crate::broadcast::views::announcement,
        crate::broadcast::views::history,
        crate::transactions::nomba_views::initialize_funding,
        crate::transactions::nomba_views::account_name,
        crate::transactions::nomba_views::dva_assign,
        crate::transactions::nomba_views::dva_confirm,
        crate::payments::nomba_withdrawal::withdrawal,
        crate::market_place::views::vendor::create_vendor,
        crate::market_place::views::vendor::vendor_status,
        crate::market_place::views::vendor::vendor_tickets,
        crate::market_place::views::events::create_event,
        crate::market_place::views::events::list_events,
        crate::market_place::views::events::event_detail,
        crate::market_place::views::events::event_public_view,
        crate::market_place::views::events::update_event,
        crate::market_place::views::events::vendor_cancel,
        crate::market_place::views::events::cancel_status,
        crate::market_place::views::events::export_attendees,
        crate::market_place::views::purchase::purchase,
        crate::market_place::views::tickets::my_tickets,
        crate::market_place::views::tickets::ticket_list,
        crate::market_place::views::tickets::my_tickets_list,
        crate::market_place::views::tickets::ticket_detail,
        crate::market_place::views::tickets::transfer_ticket,
        crate::market_place::views::tickets::cancel_ticket,
        crate::market_place::views::scan::scan_ticket,
        crate::market_place::views::scan::scan_stats,
        crate::market_place::views::scan::my_assignments,
        crate::market_place::views::scan::add_scanner,
        crate::market_place::views::withdrawal::verify_account_name,
        crate::market_place::views::withdrawal::withdraw,
        crate::market_place::views::withdrawal::withdrawal_history,
    ),
    components(schemas(
        crate::accounts::serializers::ProfilePublic,
        crate::accounts::serializers::SignUpBody,
        crate::accounts::serializers::OtpBody,
        crate::accounts::serializers::LoginBody,
        crate::accounts::serializers::EmailOnlyBody,
        crate::accounts::serializers::ResetConfirmBody,
        crate::accounts::serializers::LogoutBody,
        crate::accounts::serializers::SetPinBody,
        crate::accounts::serializers::ChangePinBody,
        crate::accounts::serializers::VerifyPinBody,
        crate::accounts::serializers::OtpOnlyBody,
        crate::accounts::serializers::NewPinBody,
        crate::accounts::serializers::LookupBody,
        crate::accounts::serializers::GoogleLoginBody,
        crate::accounts::serializers::DvaAssignBody,
        crate::wallet::serializers::WalletPublic,
        crate::transactions::serializers::WalletTransactionPublic,
        crate::transactions::serializers::InitializeFundingBody,
        crate::transactions::serializers::DvaRefreshBody,
        crate::transactions::serializers::AccountNameBody,
        crate::payments::serializers::AirtimeBody,
        crate::payments::serializers::DataBody,
        crate::payments::serializers::CableBody,
        crate::payments::serializers::ElectricityBody,
        crate::payments::serializers::PhoneOnlyBody,
        crate::payments::serializers::JambBody,
        crate::payments::serializers::CustomerVerifyBody,
        crate::payments::serializers::GroupPaymentBody,
        crate::payments::serializers::InternalTransferBody,
        crate::payments::serializers::WithdrawalBody,
        crate::payments::serializers::WithdrawalPublic,
        crate::payments::serializers::ContributionPublic,
        crate::payments::serializers::GroupPaymentPublic,
        crate::user_preference::serializers::DvaInfo,
        crate::user_preference::serializers::UpdatePreferenceBody,
        crate::notifications::serializers::NotificationPublic,
        crate::bonus::serializers::BonusHistoryPublic,
        crate::bonus::serializers::BonusCampaignPublic,
        crate::bonus::serializers::ReferralPublic,
        crate::bonus::serializers::ReferralApplyBody,
        crate::autotopup::serializers::AutoTopUpPublic,
        crate::autotopup::serializers::AutoTopUpHistoryPublic,
        crate::autotopup::serializers::AutoTopUpCreateBody,
        crate::loyalty_market::serializers::RewardPublic,
        crate::loyalty_market::serializers::RedemptionPublic,
        crate::group_payment::serializers::GroupListEntry,
        crate::group_payment::serializers::GroupMemberPublic,
        crate::group_payment::serializers::CreateGroupBody,
        crate::group_payment::serializers::AddMemberBody,
        crate::group_payment::serializers::JoinGroupBody,
        crate::group_payment::serializers::GroupIdBody,
        crate::group_payment::serializers::UpdateGroupBody,
        crate::affiliate::serializers::AffiliateApplyBody,
        crate::affiliate::serializers::AffiliateLinkCreateBody,
        crate::affiliate::serializers::AffiliateAttributionBody,
        crate::affiliate::serializers::AffiliateStatusPublic,
        crate::affiliate::serializers::AffiliateLinkPublic,
        crate::affiliate::serializers::AffiliateSalePublic,
        crate::support::serializers::AttachmentPublic,
        crate::support::serializers::MessagePublic,
        crate::support::serializers::TicketPublic,
        crate::support::serializers::AdminTicketPublic,
        crate::support::serializers::CreateTicketBody,
        crate::support::serializers::AddMessageBody,
        crate::support::serializers::AdminUpdateBody,
        crate::broadcast::serializers::BroadcastPublic,
        crate::market_place::serializers::TicketTypePublic,
        crate::market_place::serializers::VendorPublicOut,
        crate::market_place::serializers::EventPublic,
        crate::market_place::serializers::IssuedTicketOut,
        crate::market_place::serializers::TicketListOut,
        crate::market_place::serializers::ActionStatus,
        crate::market_place::serializers::RefundInfo,
        crate::market_place::serializers::TicketDetailOut,
        crate::market_place::serializers::EventWithdrawalPublic,
    )),
)]
pub struct ApiDoc;
