# Generated by Django 5.2.6 on 2025-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('payment', 'Payment'), ('warning', 'Warning'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('contribution', 'Contribution'), ('wallet', 'Wallet'), ('group', 'Group')], default='info', max_length=20),
        ),
    ]
